project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_API_TOKEN"
preserve_hierarchy: true
files:
  # JSON translation files
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  # ProcessForce
  - source: /docs/processforce/current/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs-processforce/current/**/%original_file_name%
  # PDC
  - source: /docs/pdc/current/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs-pdc/current/**/%original_file_name%
  # WMS
  - source: /docs/wms/current/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs-wms/current/**/%original_file_name%
# Documentation template:
# - source: /docs/<name>/current/**/*
#   translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs-<name>/current/**/%original_file_name%
# For versioned docs:
# - source: /docs/<name>/versioned/<name>_versioned_docs/**/*
#   translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs-<name>/**/%original_file_name%
